fixed parsing bugs POC
Eran-YT/RegistryPerformanceViewer pull request #14
Opened 2022-02-12 11:03 UTC by ghsi011

it works now
- Replaced all nonlegal path chars with _
- If the counter type is a base counter (so there is no counter name) returns the type name as the counter name (https://docs.microsoft.com/en-us/windows/win32/wmisdk/base-counter-types)
- If there is no counter name and the type is not a base type "counter name not found" is returned as the name

2022-02-15 18:30 UTC, Eran-YT requested changes

2022-02-15 18:30 UTC, Eran-YT commented on RegistryPerformanceViewer/Utils.cpp
> +        if (invalid_chars.contains(wchar))
{ in same line as if

2022-02-15 18:30 UTC, Eran-YT commented on RegistryPerformanceViewerLib/CounterNames.cpp
> +    switch (counter_type) {
These counters don’t have names?

2022-02-19 09:26 UTC, ghsi011 commented on RegistryPerformanceViewerLib/CounterNames.cpp
> +    switch (counter_type) {
no. ideally they should have the strings I give them appended to the name of the counter they are referring to, though I have yet to look into that

2022-03-01 18:05 UTC, Eran-YT approved these changes

2022-03-01 18:05 UTC, merged